import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './components/navbar'
import Sidebar from './components/Sidebar'
import { cn } from '@/lib/utils'
import { Provider } from 'react-redux'
import { store } from '@/lib/store'
import { StoreProvider } from '@/lib/Provider'
import AuthorizedLayout from './Authorized'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}
const fontSans = Inter({
  subsets: ['latin'],
  variable: '--font-sans'
})

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <StoreProvider>
      <html lang='en' suppressHydrationWarning>
        <body
          className={cn(
            'min-h-screen bg-background font-sans antialiased p-0 m-0 overflow-hidden',
            fontSans.variable
          )}
        >
          <AuthorizedLayout>{children}</AuthorizedLayout>
        </body>
      </html>
    </StoreProvider>
  )
}
