import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './components/navbar'
import Sidebar from './components/Sidebar'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}
const fontSans = Inter({
  subsets: ['latin'],
  variable: '--font-sans'
})

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased p-0 m-0 overflow-hidden',
          fontSans.variable
        )}
      >
        <div className='flex w-full h-full '>
          <div className='w-[250px] h-full flex items-center'>
            <Sidebar />
          </div>
          <div className='bg-[#F5F6F8] flex items-start w-full h-screen flex-col px-2 py-2 '>
            <NavBar />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
// ;<div>
//   <Toaster position='bottom-left' />
// </div>
