import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { StoreProvider } from '@/lib/Provider'
import AuthorizedLayout from './Authorized'
import { cn } from '@/lib/utils'
import Sidebar from './components/Sidebar'
import NavBar from './components/navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const fontSans = Inter({
  subsets: ['latin'],
  variable: '--font-sans'
})

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <div>
          {/* {auth?.auth?.isAuthenticated ? ( */}
          <div className='flex w-full h-full '>
            <div className='w-[250px] h-full flex items-center'>
              <Sidebar />
            </div>
            <div className='bg-[#F5F6F8] flex items-start w-full h-screen flex-col px-2 py-2 '>
              <NavBar />
              {children}
            </div>
          </div>
          {/* ) : ( */}
          {/* <Login/> */}
          {/* )} */}
        </div>
      </body>
    </html>
  )
}
